export { buildDeck } from './cards/deck.js'
export { programFor } from './cards/effects.js'
export { canPlayCard } from './cards/matching.js'
export { applyChessMove, fenForArmy, isArmyInCheck, legalChessMoves } from './chess/adapter.js'
export { createGame } from './game/create-game.js'
export { getLegalActionMoves, getLegalBasicMoves } from './game/legal-intents.js'
export { evaluateOutcome, type GameOutcome } from './game/outcome.js'
export { positionKey } from './game/position-key.js'
export { projectPlayerView, type PlayerGameView } from './game/projection.js'
export { hashGameState, replayGame, type ReplayCheckpoint, type ReplayResult } from './game/replay.js'
export { applyIntent, getLegalReinforcementOptions, type ReinforcementOption } from './game/reducer.js'
export { hashSeed, nextRandom, shuffleWithSeed } from './random/seeded.js'
export { defaultRules } from './ruleset/default-preset.js'
export { resolveRuleSnapshot, standardPreset } from './ruleset/preset-catalog.js'
export { parseRuleSnapshot, RuleSnapshotSchema } from './ruleset/schema.js'
export { buildTestState } from './testing/build-state.js'
